---
title: "Refatorando os códigos"
author: "Doriedson"
date: "2025-05-01"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(ggplot2)
require(pracma)
require(matrixStats)

```

*Cada chunk deste arquivo foi idealizada para ser executada uma vez na mesma ordem em que se encontra.*

### Versão de 'Weibull_Carta.R'

```{r função da tabela xbarra}
clear()

weibull_carta_xbar = function(gama0=2, delta0=2,
                              gama1=c(.1, .5, 1, 1.5, 2, 2.5, 3, 4, 5, 6),
                              n=5, corridas=50*10**6, vetordelta){
  # Essa função faz a Tabela 1 (e as correlatas do apêndice): Valores de ARL's obtidos para análise de desempenho
  # do gráfico de X_barra (mudança bidirecional)
  
  # gama0 e delta0 são os Parâmetros sob controle.
  # gama1 e vetordelta (='delta1') são os parâmetros fora de controle
  # n é o tamanho amostral
  # corridas é a quantidade de repetição em cada iteração
  
  # Média da distribuição
  mu0 <- gama0*(gamma(1/delta0+1))
  
  # Desvio padrão
  Sigma20 <- (gama0^2)*(gamma(2/delta0+1)-(gamma(1/delta0+1)^2))
  Sigma0 <- Sigma20^0.5
  
  
  ## Distribuição Sob H0 (sob controle)
  
  SC0 <- (matrix(rweibull(n*corridas, delta0, gama0), n, corridas))
  SCmean0 <- colMeans(SC0) #Média das corridas amostras
  
  # Limites de Controle
  L<-quantile(SCmean0, c(pnorm(-3), 1-pnorm(-3)))
  LSC=L[[2]]
  LIC=L[[1]]
  
  ARL0<-1/(mean(SCmean0 <= LIC) + (mean(SCmean0 >= LSC)))

  tabela = data.frame(matrix(0, ncol=7))
  colnames(tabela) <- c("$gamma_1$", "$delta_1$", "$ARL_1$",
                         "$mu_1$", "$sigma_1$", "$desvio$", "$d(%)$")
  for(delta1 in vetordelta){
    for(valor in gama1){
      # Distribuição sob H1 (Fora de Controle)
      mu1 <- valor*(gamma(1/delta1+1))
      Sigma21 <- (valor^2)*(gamma(2/delta1+1)-(gamma(1/delta1+1)^2))
      Sigma1 <- Sigma21^0.5
      
      # Distribuição Sob H1 (sob controle)
      SC1<-(matrix(rweibull(n*corridas, delta1, valor),n,corridas)) #Corridas Amostras de tamanho n
      SCmean1<-colMeans(SC1) #Mean das corridas amostras
      
      ARL1 <- 1/(mean(SCmean1<=LIC) + (mean(SCmean1>=LSC)))
      
      # Cálculo do desvio (diferença absoluta das médias) e de d (diferença relativa)
      desvio = mu0 - mu1
      d = ifelse(desvio/mu0 < 1, round(desvio/mu0, 2)*-100, round(desvio/mu0, 2)*100)
      tabela = rbind(tabela, c(valor, delta1,
                               round(ARL1, 4), round(mu1, 4),
                               round(Sigma1, 4), round(desvio, 4), d))
      # As casas decimais serão formatadas na planilha
    }
    cat('\nFeito: delta1=', delta1)
    }
    
    cat("\nSob controle\n\n")
    print(data.frame(valor=c('gama_0' = round(gama0, 4), 'delta_0'=round(delta0, 4),
                             'ARL_0' = round(ARL0, 4), 'mu_0' = round(mu0, 4),
                             'sigma_0'= round(Sigma0, 4), 'LIC' = round(LIC, 4),
                             'LSC' = round(LSC, 4))))
  tabela <- tabela[-1, ]
  
  return(tabela)
}

```

### Tabela 1

```{r tabela 1, eval=FALSE}
# Para o número de corridas padrão cada iteração demora, em média, 5 min.
set.seed(2025)
for(x in c(.5, 1, 1.5, 2, 3, 5, 10, 20)){
  tic()
  
  tab = weibull_carta_xbar(vetordelta = x)
  #write.csv(tab, file="tabela1.csv", append = TRUE)
  write.table(tab, "tabela1.csv", sep = ",", col.names = !file.exists("tabela1.csv"),
              row.names = F, append = T)
  
  toc()
}

# gama_0	2.0000			
# delta_0	2.0000			
# ARL_0	370.3978			
# mu_0	1.7725			
# sigma_0	0.9265			
# LIC	0.7094			
# LSC	3.1526

```

### Tabelas apêndice A

```{r tabela a1, eval=FALSE}
# Para o número de corridas padrão cada iteração demora, em média, 5 min.
set.seed(2025)
for(x in c(.5, 1, 1.5, 2, 3, 5, 10, 20)){
  tic()
  
  tab = weibull_carta_xbar(gama0 = 2, delta0 = 3, vetordelta = x)
  #write.csv(tab, file="tabela1.csv", append = TRUE)
  write.table(tab, "tabela_a1.csv", sep = ",", col.names = !file.exists("tabela_a1.csv"),
              row.names = F, append = T)
  
  toc()
}

# gama_0	2.0000			
# delta_0	3.0000			
# ARL_0	370.3978			
# mu_0	1.7860			
# sigma_0	0.6491			
# LIC	0.9600			
# LSC	2.6735

```

```{r tabela a2, eval=FALSE}
# Para o número de corridas padrão cada iteração demora, em média, 5 min.
set.seed(2025)
for(x in c(.5, 1, 1.5, 2, 3, 5, 10, 20)){
  tic()
  
  tab = weibull_carta_xbar(gama0 = .5, delta0 = 1, vetordelta = x)
  #write.csv(tab, file="tabela1.csv", append = TRUE)
  write.table(tab, "tabela_a2.csv", sep = ",", col.names = !file.exists("tabela_a2.csv"),
              row.names = F, append = T)
  
  toc()
}
 
# gama_0	0.5000			
# delta_0	1.0000			
# ARL_0	370.3978			
# mu_0	0.5000			
# sigma_0	0.5000			
# LIC	0.0791			
# LSC	1.4389	

```

```{r tabela a3, eval=FALSE}
# Para o número de corridas padrão cada iteração demora, em média, 5 min.
set.seed(2025)
for(x in c(.5, 1, 1.5, 2, 3, 5, 10, 20)){
  tic()
  
  tab = weibull_carta_xbar(gama0 = 3, delta0 = 6, vetordelta = x)
  #write.csv(tab, file="tabela1.csv", append = TRUE)
  write.table(tab, "tabela_a3.csv", sep = ",", col.names = !file.exists("tabela_a3.csv"),
              row.names = F, append = T)
  
  toc()
}

# gama_0	3.0000			
# delta_0	6.0000			
# ARL_0	370.3978			
# mu_0	2.7832			
# sigma_0	0.5393			
# LIC	2.0133			
# LSC	3.4486	

```


```{r tabela a4, eval=FALSE}
# Para o número de corridas padrão cada iteração demora, em média, 5 min.
set.seed(2025)
for(x in c(.5, 1, 1.5, 2, 3, 5, 10, 20)){
  tic()
  
  tab = weibull_carta_xbar(gama0 = 50, delta0 = 25, vetordelta = x)
  #write.csv(tab, file="tabela1.csv", append = TRUE)
  write.table(tab, "tabela_a4.csv", sep = ",", col.names = !file.exists("tabela_a4.csv"),
              row.names = F, append = T)
  
  toc()
}

# gama_0	50.0000			
# delta_0	25.0000			
# ARL_0	370.3978			
# mu_0	48.9219			
# sigma_0	2.4413			
# LIC	45.0241			
# LSC	51.6518

```


#### Graficamente

```{r grafico cms}
dados = read.csv('tabela1_50mi.csv')
dados <- dados[, c(1:3)]
colnames(dados) <- c('Gama1', 'Delta1', 'ARL1')

x = dados[1:10, 1]

ggplot(dados[1:30, ], aes(x=Gama1, y=ARL1, group = Delta1, colour=factor(Delta1))) +
  geom_point() +
  geom_line() +
  labs(y = expression(CMS[1]), x = expression(gamma[1]), colour = expression(delta[1])) +
  scale_x_continuous(breaks = dados[1:10,1]) +
  theme_classic()

```


```{r grafico cms II}
plot(x=x, y=dados[1:10, 3], 'b', ylim=c(min(dados[, 3]), 45),
    pch = 16, cex = .5, ylab = "ARL_1")

lines(x = x, y = dados[11:20, 3], 'b', pch = 16, cex = .5, col='blue')
lines(x = x, y = dados[21:30, 3], 'b', pch = 16, cex = .5, col='red')
#lines(x = x, y = dados[31:40, 3], 'b')

par(mfrow=c(2,2))
plot(x = x, y = dados[41:50, 3], 'b', pch=16, cex = .5)
plot(x = x, y = dados[51:60, 3], 'b', pch=16, cex = .5)
plot(x = x, y = dados[61:70, 3], 'b', pch=16, cex = .5)
plot(x = x, y = dados[71:80, 3], 'b', pch=16, cex = .5)


```

```{r grafico de cms por desvio}
dados = read.csv('tabela1.csv')
dados <- dados[, c(2,3,4,8)]
colnames(dados) <- c('Gama1', 'Delta1', 'ARL1', 'd')

g1 = ggplot(dados, aes(x=d, y=ARL1, group = d, colour=d)) +
  geom_point() +
  xlim(c(-1,1)*100) +
  ylim(0, 600) +
  labs(y = expression(CMS[1]), x = 'Desvio da média (%)',
       colour = 'Desvio da\nmédia (%)') +
  #scale_fill_viridis_b()
  #scale_fill_brewer(palette = 'Set1') +
  #scale_x_continuous(breaks = dados[1:10,1]) +
  theme_classic()

g1

#g1 + scale_fill_distiller(palette = "Spectral")
#g1 + scale_color_brewer(palette = 'Set2')

```

## Versão de 'Weibull_Carta_Conjunta.R'

### Tabela 3

```{r geração dos valores e cálculo dos limites}
clear()

set.seed(2025)

tic()

#Parametros sob controle
gamma0<-2
delta0<-2

n=5
mu0<-gamma0*(gamma(1/delta0+1))
Sigma20<-(gamma0^2)*(gamma(2/delta0+1)-(gamma(1/delta0+1)^2))
Sigma0<-Sigma20^0.5

# DistribuiçÃo Sob H0 (sob controle)
corridas<-50000000

# Corridas Amostras de tamanho n
SC0<-(matrix(rweibull(n*corridas, delta0, gamma0), n, corridas))

# Média e variância das corridas amostras
SCmean0<-colMeans(SC0) 
SCvar0<-colVars(SC0)

# Limites de Controle
## Será criada uma matriz com as estatísticas listadas abaixo, essas serão
## calculadas a partir de cada quantil z.

z<-seq(0.00012, 0.0010, 0.000005) # precisa avaliar caso a caso
zt=length(z)
H0=matrix(0,zt,7)
for (v in 1:zt) {
  v1=z[v]
  Lm<-quantile(SCmean0, c(v1, 1-v1))
  Lv<-quantile(SCvar0, c(v1, 1-v1))
  LSa<-Lm[[2]]
  LIa<-Lm[[1]]
  LSb<-Lv[[2]]
  LIb<-Lv[[1]]
  
  zz<-mean(SCmean0<=LIa | SCmean0>=LSa | SCvar0<=LIb | SCvar0>=LSb)
  zz=1/zz
  erro=abs(zz-370.4)
  H0[v, 1]=v1
  H0[v, 2]=erro
  H0[v, 3]=zz
  H0[v, 4]=LSa
  H0[v, 5]=LIa
  H0[v, 6]=LSb
  H0[v, 7]=LIb
}

H0f<-sortrows(H0, 2)

ARL0<-H0f[1, 3]

toc() # 541 segundos

```


```{r Laço}
tic()

# Parametros fora controle
vetorgama <- c(.1, .5, 1, 1.5, 2, 2.5, 3, 4, 5, 6)
vetordelta <- c(.5, 1, 1.5, 2, 3, 5, 10, 20)


for(delta1 in vetordelta){
  resultados = matrix(0, ncol=8, dimnames = list(
    c(''),
    c('$gamma_1$', '$delta_1$', 'LSa', 'LIa',
      'LSb', 'LIb', '$ARL_0$', '$ARL_1_conjunta$')))
  
  for(gamma1 in vetorgama){
    # Corridas Amostras de tamanho n
    SC1 <- (matrix(rweibull(n*corridas, delta1, gamma1), n, corridas))
    
    SCmean1<-colMeans(SC1)
    SCvar1<-colVars(SC1)
    LSa<-H0f[1, 4]
    LIa<-H0f[1, 5]
    LSb<-H0f[1, 6]
    LIb<-H0f[1, 7]

    zz1<-mean(SCmean1<=LIa | SCmean1>=LSa | SCvar1<=LIb | SCvar1>=LSb)
    ARL1=1/zz1
    
    da_vez = c(gamma1, delta1, LSa, LIa, LSb, LIb, ARL0, ARL1)
    
    resultados = rbind(resultados, da_vez)
    cat("\nFeito: gama1=", gamma1)
  }
  
  # Escrevendo os resultados em um arquivo .csv
  write.table(resultados[-1, ], "tabela_3.csv", sep = ",",
              col.names = !file.exists("tabela_3.csv"),
              row.names = F, append = T)
  
  cat("\n\t\tFeito: delta_1=", delta1)
}

#cat('Limite Superior Media Conjunta=', LSa, "\n")
#cat('Limite Inferior Media Conjunta =', LIa, "\n")
#cat('Limite Superior VarianciaConjunta =', LSb, "\n")
#cat('Limite Inferior VarianciaConjunta =', LIb, "\n")
#cat('ARL0=', ARL0, "\n")
#cat('ARL1=', ARL1, "\n")

toc() # 2790 segundos

```

### Tabela 4

```{r geração dos valores e cálculo dos limites tab4}
clear()

set.seed(2025)

tic()

#Parametros sob controle
gamma0 <- 2
delta0 <- 3
n=5
mu0<-gamma0*(gamma(1/delta0+1))
Sigma20<-(gamma0^2)*(gamma(2/delta0+1)-(gamma(1/delta0+1)^2))
Sigma0<-Sigma20^0.5

# DistribuiçÃo Sob H0 (sob controle)
corridas<-50000000

# Corridas Amostras de tamanho n
SC0<-(matrix(rweibull(n*corridas, delta0, gamma0), n, corridas))

# Média e variância das corridas amostras
SCmean0<-colMeans(SC0) 
SCvar0<-colVars(SC0)

# Limites de Controle
## Será criada uma matriz com as estatísticas listadas abaixo, essas serão
## calculadas a partir de cada quantil z.

z<-seq(0.00012, 0.0010, 0.000005) # precisa avaliar caso a caso
zt=length(z)
H0=matrix(0,zt,7)
for (v in 1:zt) {
  v1=z[v]
  Lm<-quantile(SCmean0, c(v1, 1-v1))
  Lv<-quantile(SCvar0, c(v1, 1-v1))
  LSa<-Lm[[2]]
  LIa<-Lm[[1]]
  LSb<-Lv[[2]]
  LIb<-Lv[[1]]
  
  zz<-mean(SCmean0<=LIa | SCmean0>=LSa | SCvar0<=LIb | SCvar0>=LSb)
  zz=1/zz
  erro=abs(zz-370.4)
  H0[v, 1]=v1
  H0[v, 2]=erro
  H0[v, 3]=zz
  H0[v, 4]=LSa
  H0[v, 5]=LIa
  H0[v, 6]=LSb
  H0[v, 7]=LIb
}

H0f<-sortrows(H0, 2)

ARL0<-H0f[1, 3]

toc() # 450 segundos

```


```{r Laço tab4}
nome = 'tabela4.csv'
tic()

# Parametros fora controle
vetorgama <- c(.1, .5, 1, 1.5, 2, 2.5, 3, 4, 5, 6)
vetordelta <- c(.5, 1, 1.5, 2, 3, 5, 10, 20)

for(delta1 in vetordelta){
  resultados = matrix(0, ncol=8, dimnames = list(
    c(''),
    c('$gamma_1$', '$delta_1$', 'LSa', 'LIa',
      'LSb', 'LIb', '$ARL_0$', '$ARL_1_conjunta$')))
  
  for(gamma1 in vetorgama){
    # Corridas Amostras de tamanho n
    SC1 <- (matrix(rweibull(n*corridas, delta1, gamma1), n, corridas))
    
    SCmean1<-colMeans(SC1)
    SCvar1<-colVars(SC1)
    LSa<-H0f[1, 4]
    LIa<-H0f[1, 5]
    LSb<-H0f[1, 6]
    LIb<-H0f[1, 7]

    zz1<-mean(SCmean1<=LIa | SCmean1>=LSa | SCvar1<=LIb | SCvar1>=LSb)
    ARL1=1/zz1
    
    da_vez = c(gamma1, delta1, LSa, LIa, LSb, LIb, ARL0, ARL1)
    
    resultados = rbind(resultados, da_vez)
    cat("\nFeito: gama_1=", gamma1)
  }
  
  # Escrevendo os resultados em um arquivo .csv
  write.table(resultados[-1, ], nome, sep = ",",
              col.names = !file.exists(nome),
              row.names = F, append = T)
  
  cat("\n\t\tFeito: delta_1=", delta1)
}

toc() # 2424 segundos

```

### Tabela 5

```{r}
clear()

set.seed(2025)

tic()

#Parametros sob controle
gamma0 <- 1/2
delta0 <- 1
n=5
mu0<-gamma0*(gamma(1/delta0+1))
Sigma20<-(gamma0^2)*(gamma(2/delta0+1)-(gamma(1/delta0+1)^2))
Sigma0<-Sigma20^0.5

# DistribuiçÃo Sob H0 (sob controle)
corridas<-50000000

# Corridas Amostras de tamanho n
SC0<-(matrix(rweibull(n*corridas, delta0, gamma0), n, corridas))

# Média e variância das corridas amostras
SCmean0<-colMeans(SC0) 
SCvar0<-colVars(SC0)

# Limites de Controle
## Será criada uma matriz com as estatísticas listadas abaixo, essas serão
## calculadas a partir de cada quantil z.

z<-seq(0.00012, 0.0010, 0.000005) # precisa avaliar caso a caso
zt=length(z)
H0=matrix(0,zt,7)
for (v in 1:zt) {
  v1=z[v]
  Lm<-quantile(SCmean0, c(v1, 1-v1))
  Lv<-quantile(SCvar0, c(v1, 1-v1))
  LSa<-Lm[[2]]
  LIa<-Lm[[1]]
  LSb<-Lv[[2]]
  LIb<-Lv[[1]]
  
  zz<-mean(SCmean0<=LIa | SCmean0>=LSa | SCvar0<=LIb | SCvar0>=LSb)
  zz=1/zz
  erro=abs(zz-370.4)
  H0[v, 1]=v1
  H0[v, 2]=erro
  H0[v, 3]=zz
  H0[v, 4]=LSa
  H0[v, 5]=LIa
  H0[v, 6]=LSb
  H0[v, 7]=LIb
}

H0f<-sortrows(H0, 2)

ARL0<-H0f[1, 3]

toc() # 555 segundos

```


```{r}
nome = 'tabela5.csv'
tic()

# Parametros fora controle
vetorgama <- c(.1, .5, 1, 1.5, 2, 2.5, 3, 4, 5, 6)
vetordelta <- c(.5, 1, 1.5, 2, 3, 5, 10, 20)

for(delta1 in vetordelta){
  resultados = matrix(0, ncol=8, dimnames = list(
    c(''),
    c('$gamma_1$', '$delta_1$', 'LSa', 'LIa',
      'LSb', 'LIb', '$ARL_0$', '$ARL_1_conjunta$')))
  
  for(gamma1 in vetorgama){
    # Corridas Amostras de tamanho n
    SC1 <- (matrix(rweibull(n*corridas, delta1, gamma1), n, corridas))
    
    SCmean1<-colMeans(SC1)
    SCvar1<-colVars(SC1)
    LSa<-H0f[1, 4]
    LIa<-H0f[1, 5]
    LSb<-H0f[1, 6]
    LIb<-H0f[1, 7]

    zz1<-mean(SCmean1<=LIa | SCmean1>=LSa | SCvar1<=LIb | SCvar1>=LSb)
    ARL1=1/zz1
    
    da_vez = c(gamma1, delta1, LSa, LIa, LSb, LIb, ARL0, ARL1)
    
    resultados = rbind(resultados, da_vez)
    cat("\nFeito: gama_1=", gamma1)
  }
  
  # Escrevendo os resultados em um arquivo .csv
  write.table(resultados[-1, ], nome, sep = ",",
              col.names = !file.exists(nome),
              row.names = F, append = T)
  
  cat("\n\t\tFeito: delta_1=", delta1)
}

toc() # 2656 segundos


```

### Tabela 6

```{r}
clear()

set.seed(2025)

tic()

# Parametros sob controle
gamma0 <- 3
delta0 <- 6
n=5
mu0<-gamma0*(gamma(1/delta0+1))
Sigma20<-(gamma0^2)*(gamma(2/delta0+1)-(gamma(1/delta0+1)^2))
Sigma0<-Sigma20^0.5

# DistribuiçÃo Sob H0 (sob controle)
corridas<-50000000

# Corridas Amostras de tamanho n
SC0<-(matrix(rweibull(n*corridas, delta0, gamma0), n, corridas))

# Média e variância das corridas amostras
SCmean0<-colMeans(SC0) 
SCvar0<-colVars(SC0)

# Limites de Controle
## Será criada uma matriz com as estatísticas listadas abaixo, essas serão
## calculadas a partir de cada quantil z.

z<-seq(0.00012, 0.0010, 0.000005) # precisa avaliar caso a caso
zt=length(z)
H0=matrix(0,zt,7)
for (v in 1:zt) {
  v1=z[v]
  Lm<-quantile(SCmean0, c(v1, 1-v1))
  Lv<-quantile(SCvar0, c(v1, 1-v1))
  LSa<-Lm[[2]]
  LIa<-Lm[[1]]
  LSb<-Lv[[2]]
  LIb<-Lv[[1]]
  
  zz<-mean(SCmean0<=LIa | SCmean0>=LSa | SCvar0<=LIb | SCvar0>=LSb)
  zz=1/zz
  erro=abs(zz-370.4)
  H0[v, 1]=v1
  H0[v, 2]=erro
  H0[v, 3]=zz
  H0[v, 4]=LSa
  H0[v, 5]=LIa
  H0[v, 6]=LSb
  H0[v, 7]=LIb
}

H0f<-sortrows(H0, 2)

ARL0<-H0f[1, 3]

toc() # 439 segundos

```


```{r}
nome = 'tabela6.csv'
tic()

# Parametros fora controle
vetorgama <- c(.1, .5, 1, 1.5, 2, 2.5, 3, 4, 5, 6)
vetordelta <- c(.5, 1, 1.5, 2, 3, 5, 10, 20)

for(delta1 in vetordelta){
  resultados = matrix(0, ncol=8, dimnames = list(
    c(''),
    c('$gamma_1$', '$delta_1$', 'LSa', 'LIa',
      'LSb', 'LIb', '$ARL_0$', '$ARL_1_conjunta$')))
  
  for(gamma1 in vetorgama){
    # Corridas Amostras de tamanho n
    SC1 <- (matrix(rweibull(n*corridas, delta1, gamma1), n, corridas))
    
    SCmean1<-colMeans(SC1)
    SCvar1<-colVars(SC1)
    LSa<-H0f[1, 4]
    LIa<-H0f[1, 5]
    LSb<-H0f[1, 6]
    LIb<-H0f[1, 7]

    zz1<-mean(SCmean1<=LIa | SCmean1>=LSa | SCvar1<=LIb | SCvar1>=LSb)
    ARL1=1/zz1
    
    da_vez = c(gamma1, delta1, LSa, LIa, LSb, LIb, ARL0, ARL1)
    
    resultados = rbind(resultados, da_vez)
    cat("\nFeito: gama_1=", gamma1)
  }
  
  # Escrevendo os resultados em um arquivo .csv
  write.table(resultados[-1, ], nome, sep = ",",
              col.names = !file.exists(nome),
              row.names = F, append = T)
  
  cat("\n\t\tFeito: delta_1=", delta1)
}

toc() # 2905 segundos

```

### Tabela 7

```{r}
clear()

set.seed(2025)

tic()

#Parametros sob controle
gamma0 <- 50
delta0 <- 25
n=5
mu0<-gamma0*(gamma(1/delta0+1))
Sigma20<-(gamma0^2)*(gamma(2/delta0+1)-(gamma(1/delta0+1)^2))
Sigma0<-Sigma20^0.5

# DistribuiçÃo Sob H0 (sob controle)
corridas<-50000000

# Corridas Amostras de tamanho n
SC0<-(matrix(rweibull(n*corridas, delta0, gamma0), n, corridas))

# Média e variância das corridas amostras
SCmean0<-colMeans(SC0) 
SCvar0<-colVars(SC0)

# Limites de Controle
## Será criada uma matriz com as estatísticas listadas abaixo, essas serão
## calculadas a partir de cada quantil z.

z<-seq(0.00012, 0.0010, 0.000005) # precisa avaliar caso a caso
zt=length(z)
H0=matrix(0,zt,7)
for (v in 1:zt) {
  v1=z[v]
  Lm<-quantile(SCmean0, c(v1, 1-v1))
  Lv<-quantile(SCvar0, c(v1, 1-v1))
  LSa<-Lm[[2]]
  LIa<-Lm[[1]]
  LSb<-Lv[[2]]
  LIb<-Lv[[1]]
  
  zz<-mean(SCmean0<=LIa | SCmean0>=LSa | SCvar0<=LIb | SCvar0>=LSb)
  zz=1/zz
  erro=abs(zz-370.4)
  H0[v, 1]=v1
  H0[v, 2]=erro
  H0[v, 3]=zz
  H0[v, 4]=LSa
  H0[v, 5]=LIa
  H0[v, 6]=LSb
  H0[v, 7]=LIb
}

H0f<-sortrows(H0, 2)

ARL0<-H0f[1, 3]

toc() # 544 segundos

```


```{r}
nome = 'tabela7.csv'

tic()

# Parametros fora controle
vetorgama <- c(.1, .5, 1, 1.5, 2, 2.5, 3, 4, 5, 6)
vetordelta <- c(.5, 1, 1.5, 2, 3, 5, 10, 20)

for(delta1 in vetordelta){
  resultados = matrix(0, ncol=8, dimnames = list(
    c(''),
    c('$gamma_1$', '$delta_1$', 'LSa', 'LIa',
      'LSb', 'LIb', '$ARL_0$', '$ARL_1_conjunta$')))
  
  for(gamma1 in vetorgama){
    # Corridas Amostras de tamanho n
    SC1 <- (matrix(rweibull(n*corridas, delta1, gamma1), n, corridas))
    
    SCmean1<-colMeans(SC1)
    SCvar1<-colVars(SC1)
    LSa<-H0f[1, 4]
    LIa<-H0f[1, 5]
    LSb<-H0f[1, 6]
    LIb<-H0f[1, 7]

    zz1<-mean(SCmean1<=LIa | SCmean1>=LSa | SCvar1<=LIb | SCvar1>=LSb)
    ARL1=1/zz1
    
    da_vez = c(gamma1, delta1, LSa, LIa, LSb, LIb, ARL0, ARL1)
    
    resultados = rbind(resultados, da_vez)
    cat("\nFeito: gama_1=", gamma1)
  }
  
  # Escrevendo os resultados em um arquivo .csv
  write.table(resultados[-1, ], nome, sep = ",",
              col.names = !file.exists(nome),
              row.names = F, append = T)
  
  cat("\n\t\tFeito: delta_1=", delta1)
}

toc() # 3153 segundos

```

### Tabelas apêndice B

```{r função da tabela s2}
clear()

weibull_carta_var = function(gama0=2, delta0=2,
                              gama1=c(.1, .5, 1, 1.5, 2, 2.5, 3, 4, 5, 6),
                              n=5, corridas=50*10**6, vetordelta){
  # Essa função faz a Tabela 1 (e as correlatas do apêndice): Valores de ARL's obtidos para análise de desempenho
  # do gráfico de X_barra (mudança bidirecional)
  
  # gama0 e delta0 são os Parâmetros sob controle.
  # gama1 e vetordelta (='delta1') são os parâmetros fora de controle
  # n é o tamanho amostral
  # corridas é a quantidade de repetição em cada iteração
  
  # Média da distribuição
  mu0 <- gama0*(gamma(1/delta0+1))
  
  # Desvio padrão
  Sigma20 <- (gama0^2)*(gamma(2/delta0+1)-(gamma(1/delta0+1)^2))
  Sigma0 <- Sigma20^0.5
  
  
  ## Distribuição Sob H0 (sob controle)
  
  SC0 <- (matrix(rweibull(n*corridas, delta0, gama0), n, corridas))
  SCmean0 <- colVars(SC0) #Média das corridas amostras
  
  # Limites de Controle
  L<-quantile(SCmean0, c(pnorm(-3), 1-pnorm(-3)))
  LSC=L[[2]]
  LIC=L[[1]]
  
  ARL0<-1/(mean(SCmean0 <= LIC) + (mean(SCmean0 >= LSC)))

  tabela = data.frame(matrix(0, ncol=7))
  colnames(tabela) <- c("$gamma_1$", "$delta_1$", "$ARL_1$",
                         "$mu_1$", "$sigma_1$", "$desvio$", "$d(%)$")
  for(delta1 in vetordelta){
    for(valor in gama1){
      # Distribuição sob H1 (Fora de Controle)
      mu1 <- valor*(gamma(1/delta1+1))
      Sigma21 <- (valor^2)*(gamma(2/delta1+1)-(gamma(1/delta1+1)^2))
      Sigma1 <- Sigma21^0.5
      
      # Distribuição Sob H1 (sob controle)
      SC1<-(matrix(rweibull(n*corridas, delta1, valor),n,corridas)) #Corridas Amostras de tamanho n
      SCmean1<-colMeans(SC1) #Mean das corridas amostras
      
      ARL1 <- 1/(mean(SCmean1<=LIC) + (mean(SCmean1>=LSC)))
      
      # Cálculo do desvio (diferença absoluta das médias) e de d (diferença relativa)
      desvio = mu0 - mu1
      d = ifelse(desvio/mu0 < 1, round(desvio/mu0, 2)*-100, round(desvio/mu0, 2)*100)
      tabela = rbind(tabela, c(valor, delta1,
                               round(ARL1, 4), round(mu1, 4),
                               round(Sigma1, 4), round(desvio, 4), d))
      # As casas decimais serão formatadas na planilha
    }
    cat('\nFeito: delta1=', delta1)
    }
    
    cat("\nSob controle\n\n")
    print(data.frame(valor=c('gama_0' = round(gama0, 4), 'delta_0'=round(delta0, 4),
                             'ARL_1' = round(ARL0, 4), 'mu_0' = round(mu0, 4),
                             'sigma_0'= round(Sigma0, 4), 'LIC' = round(LIC, 4),
                             'LSC' = round(LSC, 4))))
  tabela <- tabela[-1, ]
  
  return(tabela)
}
```


```{r}
aux = weibull_carta_var(vetordelta = c(.5, 1, 1.5, 2))

```

```{r}
aux
```



```{r}
# Para tabelas B
# Carta de S^2

gamma0<-2
delta0<-2
#Par?metros fora controle
#gamma1<-1
#delta1<-1

# # # # # # # # # # # # # # # # #
n=5
mu0<-gamma0*(gamma(1/delta0+1))
Sigma20<-(gamma0^2)*(gamma(2/delta0+1)-(gamma(1/delta0+1)^2))
Sigma0<-Sigma20^0.5
#Distribui??o Sob H0 (sob controle)
corridas<-50000000
SC0<-(matrix(rweibull(n*corridas,delta0,gamma0),n,corridas)) #Corridas Amostras de tamanho n
SCvar0<-colVars(SC0)
#Limites de Controle

z<-seq(0.00012,0.0010,0.000005) #precisa avaliar caso a caso
zt=length(z)
H0=matrix(0, zt, 5)
for (v in 1:zt) {
  v1=z[v]
  Lv<-quantile(SCvar0,c(v1,1-v1))
  LSb<-Lv[[2]]
  LIb<-Lv[[1]]
  
  zz<-mean(SCvar0<=LIb | SCvar0>=LSb)
  zz=1/zz
  erro=abs(zz-370.4)
  H0[v,1]=v1
  H0[v,2]=erro
  H0[v,3]=zz
  H0[v,4]=LSb
  H0[v,5]=LIb
}

H0f<-sortrows(H0, 2)

ARL0<-H0f[1,3]
# # # # # # # # # # # # # # # # # #


SC1<-(matrix(rweibull(n*corridas,delta1,gamma1),n,corridas)) #Corridas Amostras de tamanho n
SCvar1<-colVars(SC1)
LSb<-H0f[1, 4]
LIb<-H0f[1, 5]

#Seria bom fazer um loop aqui para aproveitar os Limites de Controle j? calculados
zz1<-mean(SCvar1<=LIb | SCvar1>=LSb)
ARL1=1/zz1
ARL1


```

### Tabela B1

```{r parte1}
clear()

set.seed(2025)

tic()

# Parâmetros sob controle
n=5
gamma0 = 2
delta0 = 2

mu0<-gamma0*(gamma(1/delta0+1))
Sigma20<-(gamma0^2)*(gamma(2/delta0+1)-(gamma(1/delta0+1)^2))
Sigma0<-Sigma20^0.5
#Distribuição Sob H0 (sob controle)
corridas<-50000000
SC0<-(matrix(rweibull(n*corridas,delta0,gamma0),n,corridas)) #Corridas Amostras de tamanho n
SCvar0<-colVars(SC0)
#Limites de Controle

z<-seq(0.00012,0.0010,0.000005) #precisa avaliar caso a caso
zt=length(z)
H0=matrix(0, zt, 5)
for (v in 1:zt) {
  v1=z[v]
  Lv<-quantile(SCvar0,c(v1,1-v1))
  LSb<-Lv[[2]]
  LIb<-Lv[[1]]
  
  zz<-mean(SCvar0<=LIb | SCvar0>=LSb)
  zz=1/zz
  erro=abs(zz-370.4)
  H0[v,1]=v1
  H0[v,2]=erro
  H0[v,3]=zz
  H0[v,4]=LSb
  H0[v,5]=LIb
}

H0f<-sortrows(H0, 2)

ARL0<-H0f[1,3]

toc() # 231 segundos

```


```{r parte2}
tic()

nome = 'carta_s2_1.csv'

# Parametros fora controle
vetorgama <- c(.1, .5, 1, 1.5, 2, 2.5, 3, 4, 5, 6)
vetordelta <- c(.5, 1, 1.5, 2, 3, 5, 10, 20)

for(delta1 in vetordelta){
  resultados = matrix(0, ncol=7, dimnames = list(
    c(''), c('$gamma_1$', '$delta_1$', '$ARL_1$',
             'mu1', 'sigma1', 'desvio', 'd(%)'))
    )
  
  for(gamma1 in vetorgama){
    # Distribuição sob H1 (Fora de Controle)
    mu1 <- gamma1*(gamma(1/delta1+1))
    Sigma21 <- (gamma1^2)*(gamma(2/delta1+1)-(gamma(1/delta1+1)^2))
    Sigma1 <- Sigma21^0.5
    
    desvio = mu0 - mu1
    d = ifelse(desvio/mu0 < 1,
               round(desvio/mu0, 2)*-100,
               round(desvio/mu0, 2)*100)
    
    # Corridas Amostras de tamanho n
    SC1 <- (matrix(rweibull(n*corridas, delta1, gamma1), n, corridas))
    
    SCvar1<-colVars(SC1)
    LSb<-H0f[1, 4]
    LIb<-H0f[1, 5]

    zz1<-mean(SCvar1<=LIb | SCvar1>=LSb)
    ARL1=1/zz1
    
    da_vez = c(gamma1, delta1, ARL1, mu1, Sigma1, desvio, d)
    
    resultados = rbind(resultados, da_vez)
    cat("\nFeito: gama_1=", gamma1)
  }
  
  # Escrevendo os resultados em um arquivo .csv
  write.table(resultados[-1, ], nome, sep = ",",
              col.names = !file.exists(nome),
              row.names = F, append = T)
  
  cat("\n\t\tFeito: delta_1=", delta1)
}

cat("\nlimite inferior=", LIb) # 0.01913291
cat("\nlimite superior=", LSb) # 4.402897
cat("\nARL_0=", ARL0) # 500

toc()

```

### Tabela B2

```{r}
clear()

set.seed(2025)

tic()

# Parâmetros sob controle
n=5
gamma0 = 2
delta0 = 3 

mu0<-gamma0*(gamma(1/delta0+1))
Sigma20<-(gamma0^2)*(gamma(2/delta0+1)-(gamma(1/delta0+1)^2))
Sigma0<-Sigma20^0.5
#Distribuição Sob H0 (sob controle)
corridas<-50000000
SC0<-(matrix(rweibull(n*corridas,delta0,gamma0),n,corridas)) #Corridas Amostras de tamanho n
SCvar0<-colVars(SC0)
#Limites de Controle

z<-seq(0.00012,0.0010,0.000005) #precisa avaliar caso a caso
zt=length(z)
H0=matrix(0, zt, 5)
for (v in 1:zt) {
  v1=z[v]
  Lv<-quantile(SCvar0,c(v1,1-v1))
  LSb<-Lv[[2]]
  LIb<-Lv[[1]]
  
  zz<-mean(SCvar0<=LIb | SCvar0>=LSb)
  zz=1/zz
  erro=abs(zz-370.4)
  H0[v,1]=v1
  H0[v,2]=erro
  H0[v,3]=zz
  H0[v,4]=LSb
  H0[v,5]=LIb
}

H0f<-sortrows(H0, 2)

ARL0<-H0f[1,3]

toc() # 241 segundos

```

```{r}
tic()

nome = 'tabela_b2.csv'

# Parametros fora controle
vetorgama <- c(.1, .5, 1, 1.5, 2, 2.5, 3, 4, 5, 6)
vetordelta <- c(.5, 1, 1.5, 2, 3, 5, 10, 20)

for(delta1 in vetordelta){
  resultados = matrix(0, ncol=7, dimnames = list(
    c(''), c('$gamma_1$', '$delta_1$', '$ARL_1$',
             'mu1', 'sigma1', 'desvio', 'd(%)'))
    )
  
  for(gamma1 in vetorgama){
    # Distribuição sob H1 (Fora de Controle)
    mu1 <- gamma1*(gamma(1/delta1+1))
    Sigma21 <- (gamma1^2)*(gamma(2/delta1+1)-(gamma(1/delta1+1)^2))
    Sigma1 <- Sigma21^0.5
    
    desvio = mu0 - mu1
    d = ifelse(desvio/mu0 < 1,
               round(desvio/mu0, 2)*-100,
               round(desvio/mu0, 2)*100)
    
    # Corridas Amostras de tamanho n
    SC1 <- (matrix(rweibull(n*corridas, delta1, gamma1), n, corridas))
    
    SCvar1<-colVars(SC1)
    LSb<-H0f[1, 4]
    LIb<-H0f[1, 5]

    zz1<-mean(SCvar1<=LIb | SCvar1>=LSb)
    ARL1=1/zz1
    
    da_vez = c(gamma1, delta1, ARL1, mu1, Sigma1, desvio, d)
    
    resultados = rbind(resultados, da_vez)
    cat("\nFeito: gama_1=", gamma1)
  }
  
  # Escrevendo os resultados em um arquivo .csv
  write.table(resultados[-1, ], nome, sep = ",",
              col.names = !file.exists(nome),
              row.names = F, append = T)
  
  cat("\n\t\tFeito: delta_1=", delta1)
}

cat("\nlimite inferior=", LIb) # 0.01026342
cat("\nlimite superior=", LSb) # 1.770131
cat("\nARL_0=", ARL0) # 500

toc()

```

### Tabela B3

```{r}
clear()

set.seed(2025)

tic()

# Parâmetros sob controle
n=5
gamma0 = 1/2
delta0 = 1

mu0<-gamma0*(gamma(1/delta0+1))
Sigma20<-(gamma0^2)*(gamma(2/delta0+1)-(gamma(1/delta0+1)^2))
Sigma0<-Sigma20^0.5
#Distribuição Sob H0 (sob controle)
corridas<-50000000
SC0<-(matrix(rweibull(n*corridas,delta0,gamma0),n,corridas)) #Corridas Amostras de tamanho n
SCvar0<-colVars(SC0)
#Limites de Controle

z<-seq(0.00012,0.0010,0.000005) #precisa avaliar caso a caso
zt=length(z)
H0=matrix(0, zt, 5)
for (v in 1:zt) {
  v1=z[v]
  Lv<-quantile(SCvar0,c(v1,1-v1))
  LSb<-Lv[[2]]
  LIb<-Lv[[1]]
  
  zz<-mean(SCvar0<=LIb | SCvar0>=LSb)
  zz=1/zz
  erro=abs(zz-370.4)
  H0[v,1]=v1
  H0[v,2]=erro
  H0[v,3]=zz
  H0[v,4]=LSb
  H0[v,5]=LIb
}

H0f<-sortrows(H0, 2)

ARL0<-H0f[1,3]

toc() # 273 segundos

```

```{r}
tic()

nome = 'tabela_b3.csv'

# Parametros fora controle
vetorgama <- c(.1, .5, 1, 1.5, 2, 2.5, 3, 4, 5, 6)
vetordelta <- c(.5, 1, 1.5, 2, 3, 5, 10, 20)

for(delta1 in vetordelta){
  resultados = matrix(0, ncol=7, dimnames = list(
    c(''), c('$gamma_1$', '$delta_1$', '$ARL_1$',
             'mu1', 'sigma1', 'desvio', 'd(%)'))
    )
  
  for(gamma1 in vetorgama){
    # Distribuição sob H1 (Fora de Controle)
    mu1 <- gamma1*(gamma(1/delta1+1))
    Sigma21 <- (gamma1^2)*(gamma(2/delta1+1)-(gamma(1/delta1+1)^2))
    Sigma1 <- Sigma21^0.5
    
    desvio = mu0 - mu1
    d = ifelse(desvio/mu0 < 1,
               round(desvio/mu0, 2)*-100,
               round(desvio/mu0, 2)*100)
    
    # Corridas Amostras de tamanho n
    SC1 <- (matrix(rweibull(n*corridas, delta1, gamma1), n, corridas))
    
    SCvar1<-colVars(SC1)
    LSb<-H0f[1, 4]
    LIb<-H0f[1, 5]

    zz1<-mean(SCvar1<=LIb | SCvar1>=LSb)
    ARL1=1/zz1
    
    da_vez = c(gamma1, delta1, ARL1, mu1, Sigma1, desvio, d)
    
    resultados = rbind(resultados, da_vez)
    cat("\nFeito: gama_1=", gamma1)
  }
  
  # Escrevendo os resultados em um arquivo .csv
  write.table(resultados[-1, ], nome, sep = ",",
              col.names = !file.exists(nome),
              row.names = F, append = T)
  
  cat("\n\t\tFeito: delta_1=", delta1)
}

cat("\nlimite inferior=", LIb) # 0.0016206
cat("\nlimite superior=", LSb) # 3.0647
cat("\nARL_0=", ARL0) # 500

toc() # 2947 segundos

```

### Tabela B4

```{r}
clear()

set.seed(2025)

tic()

# Parâmetros sob controle
n=5
gamma0 = 3
delta0 = 6

mu0<-gamma0*(gamma(1/delta0+1))
Sigma20<-(gamma0^2)*(gamma(2/delta0+1)-(gamma(1/delta0+1)^2))
Sigma0<-Sigma20^0.5
#Distribuição Sob H0 (sob controle)
corridas<-50000000
SC0<-(matrix(rweibull(n*corridas,delta0,gamma0),n,corridas)) #Corridas Amostras de tamanho n
SCvar0<-colVars(SC0)
#Limites de Controle

z<-seq(0.00012,0.0010,0.000005) #precisa avaliar caso a caso
zt=length(z)
H0=matrix(0, zt, 5)
for (v in 1:zt) {
  v1=z[v]
  Lv<-quantile(SCvar0,c(v1,1-v1))
  LSb<-Lv[[2]]
  LIb<-Lv[[1]]
  
  zz<-mean(SCvar0<=LIb | SCvar0>=LSb)
  zz=1/zz
  erro=abs(zz-370.4)
  H0[v,1]=v1
  H0[v,2]=erro
  H0[v,3]=zz
  H0[v,4]=LSb
  H0[v,5]=LIb
}

H0f<-sortrows(H0, 2)

ARL0<-H0f[1,3]

toc() # 238 segundos

```


```{r}
tic()

nome = 'tabela_b4.csv'

# Parametros fora controle
vetorgama <- c(.1, .5, 1, 1.5, 2, 2.5, 3, 4, 5, 6)
vetordelta <- c(.5, 1, 1.5, 2, 3, 5, 10, 20)

for(delta1 in vetordelta){
  resultados = matrix(0, ncol=7, dimnames = list(
    c(''), c('$gamma_1$', '$delta_1$', '$ARL_1$',
             'mu1', 'sigma1', 'desvio', 'd(%)'))
    )
  
  for(gamma1 in vetorgama){
    # Distribuição sob H1 (Fora de Controle)
    mu1 <- gamma1*(gamma(1/delta1+1))
    Sigma21 <- (gamma1^2)*(gamma(2/delta1+1)-(gamma(1/delta1+1)^2))
    Sigma1 <- Sigma21^0.5
    
    desvio = mu0 - mu1
    d = ifelse(desvio/mu0 < 1,
               round(desvio/mu0, 2)*-100,
               round(desvio/mu0, 2)*100)
    
    # Corridas Amostras de tamanho n
    SC1 <- (matrix(rweibull(n*corridas, delta1, gamma1), n, corridas))
    
    SCvar1<-colVars(SC1)
    LSb<-H0f[1, 4]
    LIb<-H0f[1, 5]

    zz1<-mean(SCvar1<=LIb | SCvar1>=LSb)
    ARL1=1/zz1
    
    da_vez = c(gamma1, delta1, ARL1, mu1, Sigma1, desvio, d)
    
    resultados = rbind(resultados, da_vez)
    cat("\nFeito: gama_1=", gamma1)
  }
  
  # Escrevendo os resultados em um arquivo .csv
  write.table(resultados[-1, ], nome, sep = ",",
              col.names = !file.exists(nome),
              row.names = F, append = T)
  
  cat("\n\t\tFeito: delta_1=", delta1)
}

cat("\nlimite inferior=", LIb) # 0.006493916
cat("\nlimite superior=", LSb) # 1.324015
cat("\nARL_0=", ARL0) # 

toc() # 2678 segundos

```

### Tabela B5

```{r}
clear()

set.seed(2025)

tic()

# Parâmetros sob controle
n=5
gamma0 = 50
delta0 = 25

mu0<-gamma0*(gamma(1/delta0+1))
Sigma20<-(gamma0^2)*(gamma(2/delta0+1)-(gamma(1/delta0+1)^2))
Sigma0<-Sigma20^0.5
#Distribuição Sob H0 (sob controle)
corridas<-50000000
SC0<-(matrix(rweibull(n*corridas,delta0,gamma0),n,corridas)) #Corridas Amostras de tamanho n
SCvar0<-colVars(SC0)
#Limites de Controle

z<-seq(0.00012,0.0010,0.000005) #precisa avaliar caso a caso
zt=length(z)
H0=matrix(0, zt, 5)
for (v in 1:zt) {
  v1=z[v]
  Lv<-quantile(SCvar0,c(v1,1-v1))
  LSb<-Lv[[2]]
  LIb<-Lv[[1]]
  
  zz<-mean(SCvar0<=LIb | SCvar0>=LSb)
  zz=1/zz
  erro=abs(zz-370.4)
  H0[v,1]=v1
  H0[v,2]=erro
  H0[v,3]=zz
  H0[v,4]=LSb
  H0[v,5]=LIb
}

H0f<-sortrows(H0, 2)

ARL0<-H0f[1,3]

toc() # 231 segundos
```

```{r}
tic()

nome = 'tabela_b5.csv'

# Parametros fora controle
vetorgama <- c(.1, .5, 1, 1.5, 2, 2.5, 3, 4, 5, 6)
vetordelta <- c(.5, 1, 1.5, 2, 3, 5, 10, 20)

for(delta1 in vetordelta){
  resultados = matrix(0, ncol=7, dimnames = list(
    c(''), c('$gamma_1$', '$delta_1$', '$ARL_1$',
             'mu1', 'sigma1', 'desvio', 'd(%)'))
    )
  
  for(gamma1 in vetorgama){
    # Distribuição sob H1 (Fora de Controle)
    mu1 <- gamma1*(gamma(1/delta1+1))
    Sigma21 <- (gamma1^2)*(gamma(2/delta1+1)-(gamma(1/delta1+1)^2))
    Sigma1 <- Sigma21^0.5
    
    desvio = mu0 - mu1
    d = ifelse(desvio/mu0 < 1,
               round(desvio/mu0, 2)*-100,
               round(desvio/mu0, 2)*100)
    
    # Corridas Amostras de tamanho n
    SC1 <- (matrix(rweibull(n*corridas, delta1, gamma1), n, corridas))
    
    SCvar1<-colVars(SC1)
    LSb<-H0f[1, 4]
    LIb<-H0f[1, 5]

    zz1<-mean(SCvar1<=LIb | SCvar1>=LSb)
    ARL1=1/zz1
    
    da_vez = c(gamma1, delta1, ARL1, mu1, Sigma1, desvio, d)
    
    resultados = rbind(resultados, da_vez)
    cat("\nFeito: gama_1=", gamma1)
  }
  
  # Escrevendo os resultados em um arquivo .csv
  write.table(resultados[-1, ], nome, sep = ",",
              col.names = !file.exists(nome),
              row.names = F, append = T)
  
  cat("\n\t\tFeito: delta_1=", delta1)
}

cat("\nlimite inferior=", LIb) # 0.006493916
cat("\nlimite superior=", LSb) # 1.324015
cat("\nARL_0=", ARL0) # 

toc() # 2523 segundos

```

